[package]
name = "codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
isahc = { version = "1.7.2", default-features = false, features = [
    "json",
    "http2",
] }
smol = "2.0.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
percent-encoding = "2.3.1"
