pub struct Joker {
    joker_type: JokerType,
    edition: Edition,
}

#[derive(Clone, Copy)]
#[repr(u8)]
pub enum JokerType {
    // Common
    Joker,
    GreedyJoker,
    LustyJoker,
    WrathfulJoker,
    GluttonousJoker,
    JollyJoker,
    ZanyJoker,
    MadJoker,
    CrazyJoker,
    DrollJoker,
    SlyJoker,
    WilyJoker,
    CleverJoker,
    DeviousJoker,
    CraftyJoker,
    HalfJoker,
    CreditCard,
    Banner,
    MysticSummit,
    EightBall,
    Misprint,
    RaisedFist,
    ChaosTheClown,
    ScaryFace,
    AbstractJoker,
    DelayedGratification,
    GrosMichel,
    EvenSteven,
    OddTodd,
    Scholar,
    BusinessCard,
    Supernova,
    RideTheBus,
    Egg,
    Runner,
    IceCream,
    Splash,
    BlueJoker,
    FacelessJoker,
    GreenJoker,
    Superposition,
    ToDoList,
    Cavendish,
    RedCard,
    SquareJoker,
    RiffRaff,
    Photograph,
    ReservedParking,
    MailInRebate,
    Hallucination,
    FortuneTeller,
    Juggler,
    Drunkard,
    GoldenJoker,
    Popcorn,
    WalkieTalkie,
    SmileyFace,
    GoldenTicket,
    Swashbuckler,
    HangingChad,
    ShootTheMoon,
    // Uncommon
    JokerStencil,
    FourFingers,
    Mime,
    CeremonialDagger,
    MarbleJoker,
    LoyaltyCard,
    Dusk,
    Fibonacci,
    SteelJoker,
    Hack,
    Pareidolia,
    SpaceJoker,
    Burglar,
    Blackboard,
    SixthSense,
    Constellation,
    Hiker,
    CardSharp,
    Madness,
    Seance,
    Vampire,
    Shortcut,
    Hologram,
    CloudNine,
    Rocket,
    MidasMask,
    Luchador,
    GiftCard,
    TurtleBean,
    Erosion,
    ToTheMoon,
    StoneJoker,
    LuckyCat,
    Bull,
    DietCola,
    TradingCard,
    FlashCard,
    SpareTrousers,
    Ramen,
    Seltzer,
    Castle,
    MrBones,
    Acrobat,
    SockAndBuskin,
    Troubadour,
    Certificate,
    SmearedJoker,
    Throwback,
    RoughGem,
    Bloodstone,
    Arrowhead,
    OnyxAgate,
    GlassJoker,
    Showman,
    FlowerPot,
    MerryAndy,
    OopsAllSixes,
    TheIdol,
    SeeingDouble,
    Matador,
    Satellite,
    Cartomancer,
    Astronomer,
    Bootstraps,
    // Rare
    Dna,
    Vagabond,
    Baron,
    Obelisk,
    BaseballCard,
    AncientJoker,
    Campfire,
    Blueprint,
    WeeJoker,
    HitTheRoad,
    TheDuo,
    TheTrio,
    TheFamily,
    TheOrder,
    TheTribe,
    Stuntman,
    InvisibleJoker,
    Brainstorm,
    DriversLicense,
    BurntJoker,
    // Legendary
    Canio,
    Triboulet,
    Yorick,
    Chicot,
    Perkeo,
}
impl JokerType {
    pub fn rarity(&self) -> Rarity {
        const FIRST_UNCOMMON: u8 = JokerType::JokerStencil as u8;
        const FIRST_RARE: u8 = JokerType::Dna as u8;
        const FIRST_LEGENDARY: u8 = JokerType::Canio as u8;

        match *self as u8 {
            0..FIRST_UNCOMMON => Rarity::Common,
            FIRST_UNCOMMON..FIRST_RARE => Rarity::Uncommon,
            FIRST_RARE..FIRST_LEGENDARY => Rarity::Rare,
            _ => Rarity::Legendary,
        }
    }
    pub fn effect(&self) -> JokerEffect {
        match *self {
            JokerType::Joker => JokerEffect::new(false, true, false, false, false, false),
            JokerType::GreedyJoker => JokerEffect::new(false, true, false, false, false, false),
            JokerType::LustyJoker => JokerEffect::new(false, true, false, false, false, false),
            JokerType::WrathfulJoker => JokerEffect::new(false, true, false, false, false, false),
            JokerType::GluttonousJoker => JokerEffect::new(false, true, false, false, false, false),
            JokerType::JollyJoker => JokerEffect::new(false, true, false, false, false, false),
            JokerType::ZanyJoker => JokerEffect::new(false, true, false, false, false, false),
            JokerType::MadJoker => JokerEffect::new(false, true, false, false, false, false),
            JokerType::CrazyJoker => JokerEffect::new(false, true, false, false, false, false),
            JokerType::DrollJoker => JokerEffect::new(false, true, false, false, false, false),
            JokerType::SlyJoker => JokerEffect::new(true, false, false, false, false, false),
            JokerType::WilyJoker => JokerEffect::new(true, false, false, false, false, false),
            JokerType::CleverJoker => JokerEffect::new(true, false, false, false, false, false),
            JokerType::DeviousJoker => JokerEffect::new(true, false, false, false, false, false),
            JokerType::CraftyJoker => JokerEffect::new(true, false, false, false, false, false),
            JokerType::HalfJoker => JokerEffect::new(false, true, false, false, false, false),
            JokerType::CreditCard => JokerEffect::new(false, false, false, false, false, true),
            JokerType::Banner => JokerEffect::new(true, false, false, false, false, false),
            JokerType::MysticSummit => JokerEffect::new(false, true, false, false, false, false),
            JokerType::EightBall => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Misprint => JokerEffect::new(false, true, false, false, false, false),
            JokerType::RaisedFist => JokerEffect::new(false, true, false, false, false, false),
            JokerType::ChaosTheClown => JokerEffect::new(false, false, false, true, false, false),
            JokerType::ScaryFace => JokerEffect::new(true, false, false, false, false, false),
            JokerType::AbstractJoker => JokerEffect::new(false, true, false, false, false, false),
            JokerType::DelayedGratification => {
                JokerEffect::new(false, false, false, false, false, true)
            }
            JokerType::GrosMichel => JokerEffect::new(false, true, false, false, false, false),
            JokerType::EvenSteven => JokerEffect::new(false, true, false, false, false, false),
            JokerType::OddTodd => JokerEffect::new(true, false, false, false, false, false),
            JokerType::Scholar => JokerEffect::new(true, true, false, false, false, false),
            JokerType::BusinessCard => JokerEffect::new(false, false, false, false, false, true),
            JokerType::Supernova => JokerEffect::new(false, true, false, false, false, false),
            JokerType::RideTheBus => JokerEffect::new(false, true, false, false, false, false),
            JokerType::Egg => JokerEffect::new(false, false, false, false, false, true),
            JokerType::Runner => JokerEffect::new(true, false, false, false, false, false),
            JokerType::IceCream => JokerEffect::new(true, false, false, false, false, false),
            JokerType::Splash => JokerEffect::new(false, false, false, true, false, false),
            JokerType::BlueJoker => JokerEffect::new(true, false, false, false, false, false),
            JokerType::FacelessJoker => JokerEffect::new(false, false, false, false, false, true),
            JokerType::GreenJoker => JokerEffect::new(false, true, false, false, false, false),
            JokerType::Superposition => JokerEffect::new(false, false, false, true, false, false),
            JokerType::ToDoList => JokerEffect::new(false, false, false, false, false, true),
            JokerType::Cavendish => JokerEffect::new(false, false, true, false, false, false),
            JokerType::RedCard => JokerEffect::new(false, true, false, false, false, false),
            JokerType::SquareJoker => JokerEffect::new(true, false, false, false, false, false),
            JokerType::RiffRaff => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Photograph => JokerEffect::new(false, false, true, false, false, false),
            JokerType::ReservedParking => JokerEffect::new(false, false, false, false, false, true),
            JokerType::MailInRebate => JokerEffect::new(false, false, false, false, false, true),
            JokerType::Hallucination => JokerEffect::new(false, false, false, true, false, false),
            JokerType::FortuneTeller => JokerEffect::new(false, true, false, false, false, false),
            JokerType::Juggler => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Drunkard => JokerEffect::new(false, false, false, true, false, false),
            JokerType::GoldenJoker => JokerEffect::new(false, false, false, false, false, true),
            JokerType::Popcorn => JokerEffect::new(false, true, false, false, false, false),
            JokerType::WalkieTalkie => JokerEffect::new(true, true, false, false, false, false),
            JokerType::SmileyFace => JokerEffect::new(false, true, false, false, false, false),
            JokerType::GoldenTicket => JokerEffect::new(false, false, false, false, false, true),
            JokerType::Swashbuckler => JokerEffect::new(false, true, false, false, false, false),
            JokerType::HangingChad => JokerEffect::new(false, false, false, false, true, false),
            JokerType::ShootTheMoon => JokerEffect::new(false, true, false, false, false, false),
            JokerType::JokerStencil => JokerEffect::new(false, false, true, false, false, false),
            JokerType::FourFingers => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Mime => JokerEffect::new(false, false, false, false, true, false),
            JokerType::CeremonialDagger => {
                JokerEffect::new(false, true, false, false, false, false)
            }
            JokerType::MarbleJoker => JokerEffect::new(false, false, false, true, false, false),
            JokerType::LoyaltyCard => JokerEffect::new(false, false, true, false, false, false),
            JokerType::Dusk => JokerEffect::new(false, false, false, false, true, false),
            JokerType::Fibonacci => JokerEffect::new(false, true, false, false, false, false),
            JokerType::SteelJoker => JokerEffect::new(false, false, true, false, false, false),
            JokerType::Hack => JokerEffect::new(false, false, false, false, true, false),
            JokerType::Pareidolia => JokerEffect::new(false, false, false, true, false, false),
            JokerType::SpaceJoker => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Burglar => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Blackboard => JokerEffect::new(false, false, true, false, false, false),
            JokerType::SixthSense => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Constellation => JokerEffect::new(false, false, true, false, false, false),
            JokerType::Hiker => JokerEffect::new(true, false, false, false, false, false),
            JokerType::CardSharp => JokerEffect::new(false, false, true, false, false, false),
            JokerType::Madness => JokerEffect::new(false, false, true, false, false, false),
            JokerType::Seance => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Vampire => JokerEffect::new(false, false, true, false, false, false),
            JokerType::Shortcut => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Hologram => JokerEffect::new(false, false, true, false, false, false),
            JokerType::CloudNine => JokerEffect::new(false, false, false, false, false, true),
            JokerType::Rocket => JokerEffect::new(false, false, false, false, false, true),
            JokerType::MidasMask => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Luchador => JokerEffect::new(false, false, false, true, false, false),
            JokerType::GiftCard => JokerEffect::new(false, false, false, false, false, true),
            JokerType::TurtleBean => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Erosion => JokerEffect::new(false, true, false, false, false, false),
            JokerType::ToTheMoon => JokerEffect::new(false, false, false, false, false, true),
            JokerType::StoneJoker => JokerEffect::new(true, false, false, false, false, false),
            JokerType::LuckyCat => JokerEffect::new(false, false, true, false, false, false),
            JokerType::Bull => JokerEffect::new(true, false, false, false, false, false),
            JokerType::DietCola => JokerEffect::new(false, false, false, true, false, false),
            JokerType::TradingCard => JokerEffect::new(false, false, false, false, false, true),
            JokerType::FlashCard => JokerEffect::new(false, true, false, false, false, false),
            JokerType::SpareTrousers => JokerEffect::new(false, true, false, false, false, false),
            JokerType::Ramen => JokerEffect::new(false, false, true, false, false, false),
            JokerType::Seltzer => JokerEffect::new(false, false, false, false, true, false),
            JokerType::Castle => JokerEffect::new(true, false, false, false, false, false),
            JokerType::MrBones => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Acrobat => JokerEffect::new(false, false, true, false, false, false),
            JokerType::SockAndBuskin => JokerEffect::new(false, false, false, false, true, false),
            JokerType::Troubadour => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Certificate => JokerEffect::new(false, false, false, true, false, false),
            JokerType::SmearedJoker => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Throwback => JokerEffect::new(false, false, true, false, false, false),
            JokerType::RoughGem => JokerEffect::new(false, false, false, false, false, true),
            JokerType::Bloodstone => JokerEffect::new(false, false, true, false, false, false),
            JokerType::Arrowhead => JokerEffect::new(true, false, false, false, false, false),
            JokerType::OnyxAgate => JokerEffect::new(false, true, false, false, false, false),
            JokerType::GlassJoker => JokerEffect::new(false, false, true, false, false, false),
            JokerType::Showman => JokerEffect::new(false, false, false, true, false, false),
            JokerType::FlowerPot => JokerEffect::new(false, false, true, false, false, false),
            JokerType::MerryAndy => JokerEffect::new(false, false, false, true, false, false),
            JokerType::OopsAllSixes => JokerEffect::new(false, false, false, true, false, false),
            JokerType::TheIdol => JokerEffect::new(false, false, true, false, false, false),
            JokerType::SeeingDouble => JokerEffect::new(false, false, true, false, false, false),
            JokerType::Matador => JokerEffect::new(false, false, false, false, false, true),
            JokerType::Satellite => JokerEffect::new(false, false, false, false, false, true),
            JokerType::Cartomancer => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Astronomer => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Bootstraps => JokerEffect::new(false, true, false, false, false, false),
            JokerType::Dna => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Vagabond => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Baron => JokerEffect::new(false, false, true, false, false, false),
            JokerType::Obelisk => JokerEffect::new(false, false, true, false, false, false),
            JokerType::BaseballCard => JokerEffect::new(false, false, true, false, false, false),
            JokerType::AncientJoker => JokerEffect::new(false, false, true, false, false, false),
            JokerType::Campfire => JokerEffect::new(false, false, true, false, false, false),
            JokerType::Blueprint => JokerEffect::new(false, false, false, true, false, false),
            JokerType::WeeJoker => JokerEffect::new(true, false, false, false, false, false),
            JokerType::HitTheRoad => JokerEffect::new(false, false, true, false, false, false),
            JokerType::TheDuo => JokerEffect::new(false, false, true, false, false, false),
            JokerType::TheTrio => JokerEffect::new(false, false, true, false, false, false),
            JokerType::TheFamily => JokerEffect::new(false, false, true, false, false, false),
            JokerType::TheOrder => JokerEffect::new(false, false, true, false, false, false),
            JokerType::TheTribe => JokerEffect::new(false, false, true, false, false, false),
            JokerType::Stuntman => JokerEffect::new(true, false, false, false, false, false),
            JokerType::InvisibleJoker => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Brainstorm => JokerEffect::new(false, false, false, true, false, false),
            JokerType::DriversLicense => JokerEffect::new(false, false, true, false, false, false),
            JokerType::BurntJoker => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Canio => JokerEffect::new(false, false, true, false, false, false),
            JokerType::Triboulet => JokerEffect::new(false, false, true, false, false, false),
            JokerType::Yorick => JokerEffect::new(false, false, true, false, false, false),
            JokerType::Chicot => JokerEffect::new(false, false, false, true, false, false),
            JokerType::Perkeo => JokerEffect::new(false, false, false, true, false, false),
        }
    }
}

pub struct JokerEffect {
    chips: bool,
    add_mult: bool,
    mult_mult: bool,
    effect: bool,
    retrigger: bool,
    economy: bool,
}
impl JokerEffect {
    pub fn new(
        chips: bool,
        add_mult: bool,
        mult_mult: bool,
        effect: bool,
        retrigger: bool,
        economy: bool,
    ) -> Self {
        Self {
            chips,
            add_mult,
            mult_mult,
            effect,
            retrigger,
            economy,
        }
    }
}

pub enum Edition {
    Base,
    Foil,
    Holographic,
    Polychrome,
    Negative,
}

pub enum Rarity {
    Common,
    Uncommon,
    Rare,
    Legendary,
}

pub enum Consumable {
    Tarot(Tarot),
    Planet(Planet),
    Spectral(Spectral),
}

pub struct Tarot {}
pub struct Planet {}
pub struct Spectral {}

pub struct Deck {}
